export enum LocationCategory {
  RESTAURANT = 'RESTAURANT',
  SIGHT = 'SIGHT',
  BAR = 'BAR',
  SPORT = 'SPORT',
  COFFEE = 'COFFEE',
  BILLIARDS = 'BILLIARDS',
  MUSEUM = 'MUSEUM',
  PARK = 'PARK',
  WORKSPACE = 'WORKSPACE',
  MALL = 'MALL',
  OTHERS = 'OTHERS',
}
