export enum NotificationType {
  ITINERARY_MODIFICATION = 'ITINERARY_MODIFICATION',
  EVENT_INVITATION = 'EVENT_INVITATION',
  EVENT_DELETE = 'EVENT_DELETE',
  EVENT_MODIFICATION = 'EVENT_MODIFICATION',
}
